config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :educations
  resources :jobs
  resources :recommendations
  resources :courses
  resources :people

  # Custom
  get 'people/:id/educations', :to => 'educations#new', :as => 'education_person'
  get 'people/:id/courses', :to => 'courses#new', :as => 'course_person'
  get 'people/:id/jobs', :to => 'jobs#new', :as => 'job_person'
end

app/views/layouts/backend/_header.html.erb
<header class="main-header">
  <%= link_to('#', class: "logo") do %>
    <span class="logo-mini"><b>RR</b>OR</span>
    <span class="logo-lg"><b>Resume</b>ROR</span>
  <% end %>

  <nav class="navbar navbar-static-top" role="navigation">

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img src="http://lorempixel.com/160/160/" class="user-image" alt="User Image">
            <span class="hidden-xs">Alexander Pierce</span>
          </a>
          <ul class="dropdown-menu">
            <li class="user-header">
              <img src="http://lorempixel.com/160/160/" class="img-circle" alt="User Image">
              <p>
                Alexander Pierce - Web Developer
                <small>Member since Nov. 2012</small>
              </p>
            </li>
            <li class="user-footer">
              <div class="pull-left">
                <%= link_to t('profile'), "#", class: "btn btn-default btn-flat" %>
              </div>
              <div class="pull-right">
                <%= link_to t('sign_out'), "#", class: "btn btn-default btn-flat" %>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/backend/_sidebar.html.erb
<aside class="main-sidebar">
  <section class="sidebar">

    <div class="user-panel">
      <div class="pull-left image">
        <img src="http://lorempixel.com/160/160/" class="img-circle" alt="User Image">
      </div>
      <div class="pull-left info">
        <p>Alexander Pierce</p>
        <%= link_to('#') do %>
          <i class="fa fa-circle text-success"></i> <%= t('online') %>
        <% end %>
      </div>
    </div>

    <ul class="sidebar-menu">
      <li class="header"><%= t('main_navigation') %></li>
      <li>
        <%= link_to(people_path) do %>
          <i class="fa fa-users"></i> <%= t('people_name') %>
        <% end %>
      </li>
      <li>
        <%= link_to(educations_path) do %>
          <i class="fa fa-university"></i> <%= t('education_name') %>
        <% end %>
      </li>
      <li>
        <%= link_to(courses_path) do %>
          <i class="fa fa-graduation-cap"></i> <%= t('courses_name') %>
        <% end %>
      </li>
      <li>
        <%= link_to(jobs_path) do %>
          <i class="fa fa-briefcase"></i> <%= t('jobs_name') %>
        <% end %>
      </li>
      <li>
        <%= link_to(recommendations_path) do %>
          <i class="fa fa-star"></i> <%= t('recommendations_name') %>
        <% end %>
      </li>
    </ul>

  </section>

</aside>