config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :educations
  resources :jobs
  resources :recommendations
  resources :courses
  resources :people

  # Custom
  get 'people/:id/educations', :to => 'educations#new', :as => 'education_person'
  get 'people/:id/courses', :to => 'courses#new', :as => 'course_person'
  get 'people/:id/jobs', :to => 'jobs#new', :as => 'job_person'
end

app/models/job.rb
class Job < ActiveRecord::Base
    belongs_to :person

    validates :company_name, :position, :description, :start_at, :person_id, :presence => true
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    before_action :set_job, only: [:show, :edit, :update, :destroy]

    # GET /jobs
    # GET /jobs.json
    def index
        @jobs = Job.all
    end

    # GET /jobs/1
    # GET /jobs/1.json
    def show
    end

    # GET /jobs/new
    def new
        @job = Job.new
    end

    # GET /jobs/1/edit
    def edit
    end

    # POST /jobs
    # POST /jobs.json
    def create
        @job = Job.new(job_params)

        respond_to do |format|
            if @job.save
              if(params[:commit_next])
                url_to = job_person_path(params[:job][:person_id])
              else
                url_to = job_person_path(params[:job][:person_id])
              end
              format.html { redirect_to url_to, notice: 'Job was successfully created.' }
              format.json { render :show, status: :created, location: @job }
            else
              format.html { render :new }
              format.json { render json: @job.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /jobs/1
    # PATCH/PUT /jobs/1.json
    def update
        respond_to do |format|
            #job_params[:job][:description] = 'modificando'
            if @job.update(job_params)
                format.html { redirect_to @job, notice: 'Job was successfully updated.' }
                format.json { render :show, status: :ok, location: @job }
            else
                format.html { render :edit }
                format.json { render json: @job.errors, status: :unprocessable_entity }
            end
        end
    end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id]).includes(:person)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
        params.require(:job).permit(:company_name, :position, :description, :start_at, :end_at, :person_id)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<div class="box-body">
  <%= form_for @job, builder: BootstrapFormBuilder do |f| %>
	<% if @job.errors.any? %>
      <div class="alert alert-danger" role="alert">
		<h2><%= t(:error_count, count: @job.errors.count) %></h2>
		<ul>
		  <% @job.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		  <% end %>
		</ul>
	  </div>
	<% end %>

	<%= label(:company_name, t('jobs.company_name') ) %>
	<%= f.bootstrap_text_field :company_name %>

	<%= label(:position, t('jobs.position') ) %>
	<%= f.bootstrap_text_field :position %>

	<%= label(:description, t('jobs.description') ) %><br>
	<%= f.bootstrap_text_area :description %>

	<%= label(:start_at, t('jobs.start') ) %>
	<%= f.bootstrap_month_picker :start_at %>

	<%= label(:end_at, t('jobs.end') ) %>
    <%= check_box_tag 'actual', false, false, style: "margin-left:10px;" %> Actual
	<%= f.bootstrap_month_picker :end_at %>

	<div class="form-group" style="display:none;">
	  <%= label(:person_id, t('jobs.person') ) %><br>
	  <%= f.bootstrap_text_field :person_id, :value => params[:id], :readonly => true %>
	</div>

    <div class="actions">
        <%= f.submit t('jobs.new.add_and_next'), :name => 'commit_next', :class => 'btn btn-default' %>
        <%= f.submit t('jobs.new.add_and_other'), :name => 'commit_other', :class => 'btn btn-default' %>
        <%= link_to 'Atrás', educations_path, class: 'btn btn-default' %>
    </div>
  <% end %>
</div>

  <script type="text/javascript">
	$('#job_description').wysihtml5();
  </script>

<script type="text/javascript">
  $(document).ready(function(){
	$('#actual').change(function(){
	  if(this.checked) {
		$('#job_end_at').val('');
		$('#job_end_at').prop('disabled', true);
	  } else {
		$('#job_end_at').removeAttr('disabled');
	  }
	});
  });
</script>

app/views/jobs/_table_info.html.erb
<table class="table table-bordered">
    <thead>
        <tr>
            <th><%= t 'jobs.company_name' %></th>
            <th><%= t 'jobs.position' %></th>
            <th><%= t 'jobs.description' %></th>
            <th><%= t 'jobs.start' %></th>
            <th><%= t 'jobs.end' %></th>
            <% if params[:controller] != 'people' %>
            <th><%= t 'jobs.person' %></th>
            <% end %>
            <th colspan="3"><%= t 'actions' %></th>
        </tr>
    </thead>
    <tbody>
        <% @jobs.each do |job| %>
        <tr>
            <td><%= job.company_name %></td>
            <td><%= job.position %></td>
            <td><%= job.description %></td>
            <td><%= job.start %></td>
            <td><%= job.end %></td>
            <% if params[:controller] != 'people' %>
            <td><%= job.person.name %></td>
            <% end %>
            <td><%= link_to t('show'), job %></td>
            <td><%= link_to t('edit'), edit_job_path(job) %></td>
            <td><%= link_to t('destroy'), job, method: :delete, data: { confirm: t('are_you_sure') } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/jobs/edit.html.erb
<div class="box-body">
    <%= render 'form' %>
</div>

app/views/jobs/index.html.erb
<div class="box-header with-border">
    <%= link_to t('.add') , new_job_path, class: 'btn btn-default' %>
</div>

<div class="box-body">
    <p id="notice"><%= notice %></p>
    <%= render 'table_info' %>
</div>

app/views/jobs/new.html.erb
<div class="box-body">
    <%= render 'form' %>
</div>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @job.company_name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @job.position %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Start:</strong>
  <%= @job.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @job.end %>
</p>

<p>
  <strong>Person:</strong>
  <%= @job.person_id %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>