config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :educations
  resources :jobs
  resources :recommendations
  resources :courses
  resources :people

  # Custom
  get 'people/:id/educations', :to => 'educations#new', :as => 'education_person'
  get 'people/:id/courses', :to => 'courses#new', :as => 'course_person'
  get 'people/:id/jobs', :to => 'jobs#new', :as => 'job_person'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        if(params[:commit_next])
          url_to = job_person_path(params[:course][:person_id])
        else
          url_to = course_person_path(params[:course][:person_id])
        end
        format.html { redirect_to url_to, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id]).includes(:person)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description, :person_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course, builder: BootstrapFormBuilder) do |f| %>
    <% if @course.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>
            <ul>
                <% @course.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= label(:name, t('courses.name') ) %>
    <%= f.bootstrap_text_field :name %>

    <%= label(:description, t('courses.description') ) %>
    <%= f.bootstrap_text_field :description %>

    <div class="form-group" style="display:none;">
        <%= f.label :person_id %>
        <%= f.bootstrap_text_field :person_id, :value => params[:id], :readonly => true %>
    </div>

    <div class="form-group">
        <%= f.submit t('courses.new.add_and_next'), :name => 'commit_next', :class => 'btn btn-default' %>
        <%= f.submit t('courses.new.add_and_other'), :name => 'commit_other', :class => 'btn btn-default' %>
        <%= link_to 'Atrás', educations_path, class: 'btn btn-default' %>
    </div>
<% end %>

app/views/courses/_table_info.html.erb
<table class="table table-bordered">
    <thead>
        <tr>
        <th><%= t 'courses.name' %></th>
        <th><%= t 'courses.description' %></th>
        <% if params[:controller] != 'people' %>
        <th><%= t 'courses.person' %></th>
        <% end %>
        <th colspan="3"><%= t 'actions' %></th>
        </tr>
    </thead>
    <tbody>
        <% @courses.each do |course| %>
        <tr>
            <td><%= course.name %></td>
            <td><%= course.description %></td>
            <% if params[:controller] != 'people' %>
            <td><%= course.person.name %></td>
            <% end %>
            <td><%= link_to t('show'), course %></td>
            <td><%= link_to t('edit'), edit_course_path(course) %></td>
            <td><%= link_to t('destroy'), course, method: :delete, data: { confirm: t('are_you_sure') } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/courses/edit.html.erb
<div class="box-body">
  <%= render 'form' %>
</div>

app/views/courses/index.html.erb
<div class="box-header with-border">
  <%= link_to t('.add') , new_course_path, class: 'btn btn-default' %>
</div>

<div class="box-body">
    <p id="notice"><%= notice %></p>
    <%= render 'table_info' %>
</div>

app/views/courses/new.html.erb
<div class="box-body">
  <%= render 'form' %>
</div>

app/views/courses/show.html.erb
<div class="box-header with-border">
    <%= link_to t('edit'), edit_course_path(@course), class: 'btn btn-default' %>
    <%= link_to t('back'), courses_path, class: 'btn btn-default' %>
</div>

<div class="box-body">
    <% if(notice) %>
        <div id="notice" class="alert alert-warning" role="alert"><%= notice %></div>
    <% end %>

    <table class="table table-bordered">
        <tr>
            <td class="td_show_attribute"><%= t 'courses.name' %></td>
            <td><%= @course.name %></td>
        </tr>
        <tr>
            <td class="td_show_attribute"><%= t 'courses.description' %></td>
            <td><%= @course.description %></td>
        </tr>
        <tr>
            <td class="td_show_attribute"><%= t 'courses.person' %></td>
            <td><%= @course.person_id %></td>
        </tr>
    </table>
</div>