config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :educations
  resources :jobs
  resources :recommendations
  resources :courses
  resources :people

  # Custom
  get 'people/:id/educations', :to => 'educations#new', :as => 'education_person'
  get 'people/:id/courses', :to => 'courses#new', :as => 'course_person'
  get 'people/:id/jobs', :to => 'jobs#new', :as => 'job_person'
end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :person
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :set_education, only: [:show, :edit, :update, :destroy]

  # GET /educations
  # GET /educations.json
  def index
    @educations = Education.all
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
  end

  # GET /educations/new
  def new
    @education = Education.new
  end

  # GET /educations/1/edit
  def edit
  end

  # POST /educations
  # POST /educations.json
  def create
    @education = Education.new(education_params)

    respond_to do |format|
      if @education.save
        if(params[:commit_next])
          url_to = course_person_path(params[:education][:person_id])
        else
          url_to = education_person_path(params[:education][:person_id])
        end

        format.html { redirect_to url_to, notice: 'Education was successfully created.' }
        format.json { render :show, status: :created, location: @education }
      else
        format.html { render :new }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /educations/1
  # PATCH/PUT /educations/1.json
  def update
    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to @education, notice: 'Education was successfully updated.' }
        format.json { render :show, status: :ok, location: @education }
      else
        format.html { render :edit }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    @education.destroy
    respond_to do |format|
      format.html { redirect_to educations_url, notice: 'Education was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education
      @education = Education.find(params[:id]).includes(:person)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_params
      params.require(:education).permit(:entity_name, :career, :start_at, :end_at, :person_id)
    end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_form.html.erb
<%= form_for(@education, builder: BootstrapFormBuilder) do |f| %>
    <% if @education.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@education.errors.count, "error") %> prohibited this education from being saved:</h2>

            <ul>
                <% @education.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= label(:entity_name, t('educations.entity_name') ) %>
    <%= f.bootstrap_text_field :entity_name %>

    <%= label(:career, t('educations.career') ) %>
    <%= f.bootstrap_text_field :career %>

    <%= f.label(:start, t('educations.start') ) %>
    <%= f.bootstrap_month_picker :start_at %>

    <%= f.label(:end, t('educations.end') ) %>
    <%= check_box_tag 'actual', false, false, style: "margin-left:10px;" %> Actual
    <%= f.bootstrap_month_picker :end_at %>

    <div class="form-group" style="display:none;">
        <%= f.label :person_id %>
        <%= f.bootstrap_text_field :person_id, :value => params[:id], :readonly => true %>
    </div>

    <div class="actions">
        <%= f.submit t('educations.new.add_and_next'), :name => 'commit_next', :class => 'btn btn-default' %>
        <%= f.submit t('educations.new.add_and_other'), :name => 'commit_other', :class => 'btn btn-default' %>
        <%= link_to 'Atrás', educations_path, class: 'btn btn-default' %>
    </div>
<% end %>

<script type="text/javascript">
    $(document).ready(function(){
        $('#actual').change(function(){
            if(this.checked) {
                $('#education_end_at').val('');
                $('#education_end_at').prop('disabled', true);
            } else {
                $('#education_end_at').removeAttr('disabled');
            }
        });
    });
</script>

app/views/educations/_table_info.html.erb
<table class="table table-bordered">
    <thead>
        <tr>
            <th><%= t 'people.entity_name' %></th>
            <th><%= t 'people.career' %></th>
            <th><%= t 'people.start' %></th>
            <th><%= t 'people.end' %></th>
            <% if params[:controller] != 'people' %>
            <th><%= t 'people.person' %></th>
            <% end %>
            <th colspan="3" align="center"><%= t 'actions' %></th>
        </tr>
    </thead>
    <tbody>
        <% @educations.each do |education| %>
        <tr>
            <td><%= education.entity_name %></td>
            <td><%= education.career %></td>
            <td><%= education.start %></td>
            <td><%= education.end %></td>
            <% if params[:controller] != 'people' %>
            <td><%= education.person.name %></td>
            <% end %>
            <td><%= link_to t('show'), education %></td>
            <td><%= link_to t('edit'), edit_education_path(education) %></td>
            <td><%= link_to t('destroy'), education, method: :delete, data: { confirm: t('are_you_sure') } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/educations/index.html.erb
<div class="box-header with-border">
    <%= link_to t('.add') , new_education_path, class: 'btn btn-default' %>
</div>

<div class="box-body">
    <p id="notice"><%= notice %></p>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th><%= t 'people.entity_name' %></th>
                <th><%= t 'people.career' %></th>
                <th><%= t 'people.start' %></th>
                <th><%= t 'people.end' %></th>
                <th><%= t 'people.person' %></th>
                <th colspan="3" align="center"><%= t 'actions' %></th>
            </tr>
        </thead>
        <tbody>
            <% @educations.each do |education| %>
            <tr>
                <td><%= education.entity_name %></td>
                <td><%= education.career %></td>
                <td><%= education.start %></td>
                <td><%= education.end %></td>
                <td><%= education.person_id %></td>
                <td><%= link_to t('show'), education %></td>
                <td><%= link_to t('edit'), edit_education_path(education) %></td>
                <td><%= link_to t('destroy'), education, method: :delete, data: { confirm: t('are_you_sure') } %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/educations/new.html.erb
<div class="box-body">
    <%= render 'form' %>
</div>

app/views/educations/show.html.erb
<div class="box-header with-border">
    <%= link_to t('edit'), edit_education_path(@education), class: 'btn btn-default' %>
    <%= link_to t('back'), educations_path, class: 'btn btn-default' %>
</div>

<div class="box-body">
    <% if(notice) %>
        <div id="notice" class="alert alert-warning" role="alert"><%= notice %></div>
    <% end %>
    <table class="table table-bordered">
        <tr>
            <td class="td_show_attribute"><%= t 'education.entity_name' %></td>
            <td><%= @education.entity_name %></td>
        </tr>
        <tr>
            <td class="td_show_attribute"><%= t 'education.career' %></td>
            <td><%= @education.career %></td>
        </tr>
        <tr>
            <td class="td_show_attribute"><%= t 'education.start' %></td>
            <td><%= @education.start %></td>
        </tr>
        <tr>
            <td class="td_show_attribute"><%= t 'education.end' %></td>
            <td><%= @education.end %></td>
        </tr>
        <tr>
            <td class="td_show_attribute"><%= t 'education.person' %></td>
            <td><%= @education.person_id %></td>
        </tr>
    </table>
</div>